name: CI

on:
  push:
  pull_request:

jobs:
  run-tests:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        python-version:
          - "3.12"
    name: Test
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests with Allure
        run: pytest --alluredir=allure-results

      - name: Install Allure CLI
        run: |
          curl -L "https://github.com/allure-framework/allure2/releases/download/2.25.0/allure-2.25.0.zip" -o allure.zip
          unzip -o allure.zip -d allure-bin
          # Explicitly add allure-bin to the PATH and set it for the current step
          echo "$(pwd)/allure-bin/allure-2.25.0/bin" >> $GITHUB_ENV

      - name: Generate Allure HTML Report
        run: |
          # PowerShell-compatible way to execute Allure from the full path
          & "$(pwd)\allure-bin\allure-2.25.0\bin\allure" generate allure-results --clean -o allure-report

      - name: Upload Allure Report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report